pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t nginx-app .'
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f apps/sample-app/'
      }
    }
  }
}
